[Desktop Entry]
Type=X-GNOME-Metatheme
Name=wal-_home_dylan_Pictures_Wallpapers_3.jpg
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=wal-_home_dylan_Pictures_Wallpapers_3.jpg
GtkTheme=wal-_home_dylan_Pictures_Wallpapers_3.jpg
IconTheme=wal-_home_dylan_Pictures_Wallpapers_3.jpg
MetacityTheme=wal-_home_dylan_Pictures_Wallpapers_3.jpg
