[Desktop Entry]
Type=X-GNOME-Metatheme
Name=wal-oomox-_home_dylan_Pictures_Wallpapers_6.jpg
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=wal-oomox-_home_dylan_Pictures_Wallpapers_6.jpg
GtkTheme=wal-oomox-_home_dylan_Pictures_Wallpapers_6.jpg
IconTheme=wal-oomox-_home_dylan_Pictures_Wallpapers_6.jpg
MetacityTheme=wal-oomox-_home_dylan_Pictures_Wallpapers_6.jpg
