#!/bin/bash
#
# Focus windows.

source ~/.cache/wal/colors.sh
color15="${color15:-#FFFFFF}"
bw="${BW:-0}"

get_wins() {
    readarray -t wins < <(lsw)
    cur="$(pfw)"
    read -ra wins <<< "${wins[@]/${cur}}"
}

case "$1" in
    next)
        get_wins
        wid="${wins[0]:-${wins[1]}}"
    ;;

    prev)
        get_wins
        wid="${wins[-1]:-${wins[-2]}}"
    ;;

    0x*) wattr "$1" && wid="$1" ;;
esac

chwb -s "$bw" -c "0x${color15/#}" "$wid"
wtf "$wid"
