#!/bin/bash
#
# Set focus on new windows.

wew | while IFS=: read -r ev wid; do
    case "$ev" in
        16) wattr o "$wid" ;;
        19) wattr o "$wid" || { center; focus "$wid"; }  ;;
        18) wattr "$(pfw)" || focus "prev"  ;;
        7)  wattr o "$wid" || focus "$wid"  ;;
    esac
done
