#!/bin/bash
#
# Fullscreen window
#
# usage: fullscreen

cur="$(pfw)"
state_file="/tmp/.win-${cur}"

if [[ -f "$state_file" ]]; then
    read -ra attr < "$state_file"
    wtp "${attr[@]}"
    rm -f "$state_file"

else
    wattr xywhi "$cur" > "$state_file"
    read -ra attr < <(wattr wh "$(lsw -r)")
    wtp 0 0 "${attr[@]}" "$cur"
fi
