#!/bin/bash
#
# Fullscreen window
#
# usage: fullscreen <wid>

cur="${1:-$(pfw)}"
state_file="/tmp/.win-${cur}"

if [[ -f "$state_file" ]]; then
    read -ra attr < "$state_file"
    wtp "${attr[@]}" "$cur"
    rm -f "$state_file"

else
    wattr xywh "$cur" > "$state_file"
    read -ra attr < <(wattr wh "$(lsw -r)")
    wtp 0 0 "${attr[@]}" "$cur"
fi
