#!/bin/bash
#
# Workspaces
#
# usage: workspace [-i] [-g ws_num] [-m ws_num]
# 	-i: Initialize workspaces. Should be called once in a startup script.
# 	-g, <ws_num>: go to the workspace specified by <ws_num>
# 	-m, <ws_num>: move the currently focused window to the worskpace specified by <ws_num>

ws_tot=5
ws_dir="/tmp/workspaces"

ws_init() {
    # Create the workspaces.
	mkdir -p "$ws_dir"

    for i in $(seq 0 "$ws_tot"); do
		:> "${ws_dir}/ws${i}"
	done

	echo 0 > "${ws_dir}/curr"
}

ws_save() {
    # Save all windows to the current workspace.
	lsw > "${ws_dir}/ws$(< "${ws_dir}/curr")"
}

move_to_ws() {
	ws_cur=$(< "${ws_dir}/curr");

    (($1 > ws_tot || $1 < 0)) && return
    (($1 == ws_cur)) && return

	ws_save

    readarray -t wins < <(lsw)
    [[ "${wins[0]}" ]] && mapw -u "${wins[@]}"

	nwins="$(< "${ws_dir}/ws${1}")"
    [[ "$nwins" ]] && mapw -m "$nwins"

	echo "$1" > "${ws_dir}/curr"
}

move_cur_win() {
    (($1 > ws_tot || $1 < 0)) && return

	curr_ws=$(< "${ws_dir}/curr");

    [[ "$1" != "$curr_ws" ]] && {
        pfw >> "${ws_dir}/ws${1}"
        mapw -u "$(pfw)"
    }
}

while getopts ":m:g:npi" opt; do
	case "$opt" in
		g) move_to_ws "$OPTARG" ;;
		m) move_cur_win "$OPTARG" ;;
		i) ws_init ;;
        *) exit ;;
	esac
done
