#!/bin/bash
#
# Workspaces

ws_tot=5
ws_dir="/tmp/workspaces"

ws_init() {
    # Create the workspaces.
	mkdir -p "$ws_dir"

    for ((i=0; i<=ws_tot; i++)); do
		:> "${ws_dir}/ws${i}"
	done

	echo "0" > "${ws_dir}/curr"
}

ws_save() {
    # Save all windows to the current workspace.
	lsw > "${ws_dir}/ws$(< "${ws_dir}/curr")"
}

move_to_ws() {
	ws_cur=$(< "${ws_dir}/curr");

    (($1 > ws_tot || $1 < 0)) && return
    (($1 == ws_cur)) && return

	ws_save

    readarray -t wins < <(lsw)
    [[ "${wins[0]}" ]] && mapw -u "${wins[@]}"

	nwins="$(< "${ws_dir}/ws${1}")"
    [[ "$nwins" ]] && mapw -m "$nwins"

	echo "$1" > "${ws_dir}/curr"
}

move_cur_win() {
    (($1 > ws_tot || $1 < 0)) && return

	curr_ws=$(< "${ws_dir}/curr");
    curr="$(pfw)"

    [[ "$1" != "$curr_ws" ]] && {
        echo "$curr" >> "${ws_dir}/ws${1}"
        mapw -u "$curr"
    }
}

while getopts ":m:g:npi" opt; do
	case "$opt" in
		g) move_to_ws "$OPTARG" ;;
		m) move_cur_win "$OPTARG" ;;
		i) ws_init ;;
        *) exit ;;
	esac
done
