#!/bin/sh
bspc config border_width		3
bspc config window_gap         40

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config initial_polarity second_child
bspc config ignore_ewmh_focus true

bspc config focused_border_color \#$white2
bspc config active_border_color \#$white2
bspc config normal_border_color \#$white2
bspc config urgent_border_color \#$white2

bspc config focused_locked_border_color \#$white2
bspc config active_locked_border_color \#$white2
bspc config normal_locked_border_color \#$white2

bspc config focused_sticky_border_color \#$white2
bspc config active_sticky_border_color \#$white2
bspc config normal_sticky_border_color \#$white2

bspc config focused_private_border_color \#$white2
bspc config active_private_border_color \#$white2
bspc config normal_private_border_color \#$white2

bspc config -m DVI-0 top_padding 20

bspc monitor DVI-0 -d $ws1 $ws2 $ws3 $ws4
bspc monitor DVI-1 -d hello

# Workspace 1
bspc rule -a Firefox desktop=$ws1 follow=no
bspc rule -a qutebrowser desktop=$ws1 follow=no

# bspc config -d $ws1 window_gap 40

# Workspace 3
bspc rule -a Wine desktop=$ws3 floating=on
bspc rule -a Hearthstone.exe desktop=$ws3 floating=on
bspc rule -a Battle.net.exe desktop=$ws3 floating=on
bspc rule -a Steam desktop=$ws3 floating=on follow=no

# Workspace 4
bspc rule -a Gimp-2.8 desktop=$ws4

# Workspace Mon2
bspc config -d hello window_gap 100

# Workspace *
bspc rule -a feh floating=on
bspc rule -a dmenu border=on
bspc rule -a thunar floating=on

# Launches mpd
mpd &

# auto usb mount
devmon &

# Compton
compton --config ~/.compton &
# compton --backend glx --paint-on-overlay --vsync opengl-swc &

# Papes
# ~/dotfiles/scripts/wallpaper.sh &
feh --bg-fill ~/Pictures/papes/9.jpg &

# lemonbar
~/dotfiles/.config/lemonbar/clock.sh &
sleep .3s &&
~/dotfiles/.config/lemonbar/workspace.sh &
sleep .3s &&
~/dotfiles/.config/lemonbar/music.sh &

~/dotfiles/afterx.sh &
