#! /bin/sh

bspc config border_width		0
bspc config window_gap         25

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config initial_polarity second_child

# bspc config focused_border_color "#FFFFFF"
# bspc config active_border_color "#459CAB"
# bspc config normal_border_color "#459CAB"
# bspc config urgent_border_color "#FFFFFF"

# bspc config focused_locked_border_color "#FFFFFF"
# bspc config active_locked_border_color "#FFFFFF"
# bspc config normal_locked_border_color "#FFFFFF"

# bspc config focused_sticky_border_color "#FFFFFF"
# bspc config active_sticky_border_color "#FFFFFF"
# bspc config normal_sticky_border_color "#FFFFFF"

# bspc config focused_private_border_color "#FFFFFF"
# bspc config active_private_border_color "#FFFFFF"
# bspc config normal_private_border_color "#FFFFFF"

bspc config -m DFP10 top_padding 20
bspc config -m eDP1 top_padding 20

# bspc monitor DFP10 -d www code game video
# bspc monitor DFP10 -d    
bspc monitor DFP10 -d    
bspc monitor DFP11 -d hello

bspc monitor eDP1 -d www code game video

bspc rule -a Firefox desktop= follow=no
bspc rule -a Wine desktop= floating=on
bspc rule -a Steam desktop= follow=no floating=on

# feh --bg-fill ~/Pictures/papes/ryuuko2.png &
nitrogen --restore &

# lemonbar
~/.dotfiles/.config/lemonbar/clock.sh &
sleep .3s &&
~/.dotfiles/.config/lemonbar/workspace.sh &
sleep .3s &&
~/.dotfiles/.config/lemonbar/music.sh &

