# Dylan's .bashrc


# Set the prompt.
export PS1
PS1="\w \[$(tput setaf 6)\]ily \[$(tput sgr0)\]"

# Add ~/bin to path
PATH="${PATH}:${HOME}/bin"
PATH="${HOME}/.gem/ruby/2.4.0/bin:${PATH}"
PATH="${PATH}:${HOME}/.local/bin/"

# Export envars.
export XDG_CONFIG_HOME="${HOME}/.config"
export STEAM_FRAME_FORCE_CLOSE=0
export EDITOR="nvim"
export SDL_VIDEO_X11_DGAMOUSE=0
export MOZ_USE_OMTC=1
export HISTCONTROL=ignoredups

# Source colors generated by wal.
source "${HOME}/.cache/wal/colors.sh"

# History completion.
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

# Check window size after every command.
shopt -s checkwinsize

# nnn
alias n=nnn
export NNN_USE_EDITOR=1
export NNN_DE_FILE_MANAGER=thunar


# ALIASES

alias steam="steam-native"
alias sxiv="sxiv -b -s f"
alias handbrake="ghb"


# OTHER

# Auto start X.
[[ -z "$DISPLAY" && "$XDG_VTNR" -eq 1 ]] && \
    exec startx -- vt1 &> /dev/null

[[ -f "${HOME}/.fzf.bash" ]] && \
    source "${HOME}/.fzf.bash"

# Import colorscheme from 'wal'
(wal -r"${VTE_VERSION:+"t"}" &)
